/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwarefacturacion;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author julio trigo
 */
public class InterfazDeCobro extends javax.swing.JFrame {

    DefaultTableModel modelo;
    float sumar = 0;
    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-YYYY");
    Date fecha = new Date();

    public InterfazDeCobro() {
        initComponents();
        NombreTxt.setEnabled(false);
        ApellidoTxt.setEnabled(false);
        RegistrarBtn.setEnabled(false);
        TelefonoTxt.setEnabled(false);
        CantidadTxt.setEnabled(false);
        CodigoTxt.setEnabled(false);
        ProductoTxt.setVisible(false);
        PrecioTxt.setVisible(false);
        AgregarBtn.setEnabled(false);
        PrecioTotal.setEditable(false);
        PagarBtn.setEnabled(false);

        setLocationRelativeTo(null);

        modelo = new DefaultTableModel();
        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Precio");
        this.ProductosTabla.setModel(modelo);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductosTabla = new javax.swing.JTable();
        CodigoTxt = new javax.swing.JTextField();
        TelefonoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CedulaTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        RegistrarBtn = new javax.swing.JButton();
        ApellidoTxt = new javax.swing.JTextField();
        TelefonoJLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CantidadTxt = new javax.swing.JTextField();
        IngresarBtn = new javax.swing.JButton();
        PrecioTotal = new javax.swing.JTextField();
        AgregarBtn = new javax.swing.JButton();
        ProductoTxt = new javax.swing.JTextField();
        PrecioTxt = new javax.swing.JTextField();
        PagarBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 153, 51));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        ProductosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ProductosTabla);

        jLabel4.setText("Codigo");

        jLabel1.setText("Cedula");

        jLabel5.setText("Cantidad");

        jLabel3.setText("Apellido");

        RegistrarBtn.setText("Registrar");
        RegistrarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarBtnMouseClicked(evt);
            }
        });
        RegistrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarBtnActionPerformed(evt);
            }
        });

        TelefonoJLabel.setText("Telefono");

        jLabel2.setText("Nombre");

        IngresarBtn.setText("Ingresar");
        IngresarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarBtnMouseClicked(evt);
            }
        });

        PrecioTotal.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        PrecioTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AgregarBtn.setText("Agregar");
        AgregarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarBtnMouseClicked(evt);
            }
        });

        PagarBtn.setText("Pagar");
        PagarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PagarBtnMouseClicked(evt);
            }
        });

        jButton1.setText("Atras");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(425, Short.MAX_VALUE)
                .addComponent(ProductoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(312, 312, 312))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PagarBtn))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(TelefonoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(IngresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TelefonoTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(CodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(CantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RegistrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AgregarBtn)))))
                        .addComponent(PrecioTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(165, 165, 165))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(CedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(IngresarBtn)
                                    .addGap(38, 38, 38)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TelefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TelefonoJLabel)
                                .addComponent(RegistrarBtn))
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CodigoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(CantidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(AgregarBtn))
                            .addGap(48, 48, 48)
                            .addComponent(PrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(PagarBtn)
                                .addComponent(jButton1)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarBtnMouseClicked

        if("".equals(CedulaTxt.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese una cedula");
        } else {
             int cedula = Integer.parseInt(CedulaTxt.getText());
             
             
            try {
            Connection xion = Conexion.getConexion();
            Statement run = xion.createStatement();
            ResultSet rs = run.executeQuery("SELECT * FROM Cliente WHERE Cedula= '" + cedula + "'");

            if (rs.next()) {
                NombreTxt.setText(rs.getString("Nombre"));
                ApellidoTxt.setText(rs.getString("Apellido"));
                CedulaTxt.setEnabled(false);
                IngresarBtn.setEnabled(false);
                CodigoTxt.setEnabled(true);
                CantidadTxt.setEnabled(true);
                AgregarBtn.setEnabled(true);
                PagarBtn.setEnabled(true);
            } else {
                NombreTxt.setEnabled(true);
                ApellidoTxt.setEnabled(true);
                RegistrarBtn.setEnabled(true);
                TelefonoJLabel.setVisible(true);
                TelefonoTxt.setEnabled(true);
                IngresarBtn.setEnabled(false);
                CodigoTxt.setEnabled(true);
                CantidadTxt.setEnabled(true);
                AgregarBtn.setEnabled(true);
                PagarBtn.setEnabled(true);

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        }
    }//GEN-LAST:event_IngresarBtnMouseClicked

    private void RegistrarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarBtnMouseClicked
        int cedula = Integer.parseInt(CedulaTxt.getText());
        String Nombre = NombreTxt.getText();
        String Apellido = ApellidoTxt.getText();
        String telefono = TelefonoTxt.getText();

        try {
            Connection xion = Conexion.getConexion();
            PreparedStatement ps = xion.prepareStatement("INSERT INTO Cliente (Nombre, Apellido, Cedula, Telefono) VALUES (?,?,?,?)");
            ps.setString(1, Nombre);
            ps.setString(2, Apellido);
            ps.setInt(3, cedula);
            ps.setString(4, telefono);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente Agregado");

            CedulaTxt.setEnabled(false);
            NombreTxt.setEnabled(false);
            ApellidoTxt.setEnabled(false);
            TelefonoTxt.setEnabled(false);

            CodigoTxt.setEnabled(true);
            CantidadTxt.setEnabled(true);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_RegistrarBtnMouseClicked

    private void RegistrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarBtnActionPerformed

    private void AgregarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarBtnMouseClicked
        int codigo = Integer.parseInt(CodigoTxt.getText());
        float cantidad = Float.parseFloat(CantidadTxt.getText());

        try {
            Connection xion = Conexion.getConexion();
            Statement run = xion.createStatement();
            ResultSet rs = run.executeQuery("SELECT * FROM Producto WHERE id_producto= '" + codigo + "'");

            if (rs.next()) {
                ProductoTxt.setText(rs.getString("Nombre"));
                PrecioTxt.setText(rs.getString("Precio"));

                float PrecioPivote = Float.parseFloat(PrecioTxt.getText());

                float PrecioXCantidad = PrecioPivote * cantidad;

                String[] compra = new String[3];
                compra[0] = ProductoTxt.getText();
                compra[1] = CantidadTxt.getText();
                compra[2] = Float.toString(PrecioXCantidad);
                modelo.addRow(compra);

                sumar = sumar + PrecioXCantidad;

                CodigoTxt.setText("");
                CantidadTxt.setText("");
                ProductoTxt.setText("");
                PrecioTxt.setText("");

            } else {
                JOptionPane.showMessageDialog(null, "No existe el coduigo del producto");
                CodigoTxt.setText("");
                CantidadTxt.setText("");
            }

            PrecioTotal.setText(Float.toString(sumar));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        
    }//GEN-LAST:event_AgregarBtnMouseClicked

    private void PagarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PagarBtnMouseClicked
        int contar = modelo.getRowCount();

        try {
            Connection xion = Conexion.getConexion();

            for (int i = 0; i < contar; i++) {
                PreparedStatement ps = xion.prepareStatement("UPDATE Producto SET Cantidad = Cantidad - " + modelo.getValueAt(i, 1) + " Where Nombre = '" + modelo.getValueAt(i, 0) + "'");
                ps.executeUpdate();

            }
            JOptionPane.showMessageDialog(null, "Compra Realizada");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
        
        //Factura
        String Nombre = NombreTxt.getText();
        String FechaActual = formato.format(fecha);
        Float total = Float.parseFloat(PrecioTotal.getText());
        try{
            
            Connection xion = Conexion.getConexion();
            PreparedStatement ps = xion.prepareStatement("INSERT INTO Facturas (Nombre_cliente, Fecha, Total) VALUES (?,?,?)");
            ps.setString(1, Nombre);
            ps.setString(2, FechaActual);
            ps.setFloat(3, total);
            ps.executeUpdate();
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }

        //Enable(True)
        CedulaTxt.setEnabled(true);
        IngresarBtn.setEnabled(true);

        //Enable(False)
        NombreTxt.setEnabled(false);
        ApellidoTxt.setEnabled(false);
        RegistrarBtn.setEnabled(false);
        TelefonoTxt.setEnabled(false);
        CantidadTxt.setEnabled(false);
        CodigoTxt.setEnabled(false);
        ProductoTxt.setVisible(false);
        PrecioTxt.setVisible(false);
        AgregarBtn.setEnabled(false);
        PrecioTotal.setEditable(false);
        PagarBtn.setEnabled(false);
        
        for(int i = contar-1; i >= 0; i-- ){
            modelo.removeRow(i);
        }
        
        //borrar todo
        CedulaTxt.setText("");
        NombreTxt.setText("");
        ApellidoTxt.setText("");
        TelefonoTxt.setText("");
        PrecioTotal.setText("");
        
        sumar = 0;
    }//GEN-LAST:event_PagarBtnMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Empleado atras = new Empleado();
        
        atras.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazDeCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazDeCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazDeCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazDeCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazDeCobro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBtn;
    private javax.swing.JTextField ApellidoTxt;
    private javax.swing.JTextField CantidadTxt;
    private javax.swing.JTextField CedulaTxt;
    private javax.swing.JTextField CodigoTxt;
    private javax.swing.JButton IngresarBtn;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JButton PagarBtn;
    private javax.swing.JTextField PrecioTotal;
    private javax.swing.JTextField PrecioTxt;
    private javax.swing.JTextField ProductoTxt;
    private javax.swing.JTable ProductosTabla;
    private javax.swing.JButton RegistrarBtn;
    private javax.swing.JLabel TelefonoJLabel;
    private javax.swing.JTextField TelefonoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
